name: CI

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main
      - master
      - develop-uat
      - feature-1234

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check repository
        run: |
          echo "CI is working"
          git --version